### PR TITLE
http => https in social networks links

### PR DESCRIPTION
**Pull request by jens1o**
quite a tiny change, but it will look better in the statusbar when hovering about the link and it saves (close to no tbh) time.

### CODE REVIEW

**Comment by TimWolla** [comment]
We should go the full circle here. There's a few instances of external links in `page.xml` and the language files as well. Would you consider updating them as well?

**Comment by jens1o** [comment]
I'd love to. I wasn't unsure whether you wanted to do that yourself, but this should actually a heads-up thing.

**Comment by dtdesign** [comment]
@jens1o Can you please update your PR to be in sync with the current master?

**Comment by jens1o** [comment]
@dtdesign done

**Pull request merged**
