### PR TITLE
added missing column wcf1_user_session.spiderID

### PR DESCRIPTION
**Pull request by mutec**
fixes #4067 which want's to use this column on line 1025 in `changeUserVirtual()`

/cc @TimWolla

### CODE REVIEW

**Review by xopez — APPROVED** [review]

**Comment by TimWolla** [comment]
No, this is not the correct fix. The correct fix is reverting `0d262d1080533b952de104f45df7cf5a360d8892` and then applying the change to the `wcf1_session` table.

I could swear I tested this.

**Comment by mutec** [comment]
> No, this is not the correct fix. The correct fix is reverting [0d262d1](https://github.com/WoltLab/WCF/commit/0d262d1080533b952de104f45df7cf5a360d8892) and then applying the change to the `wcf1_session` table.
Damn, it was a 50:50 chance. :D

**Comment by TimWolla** [comment]
> Damn, it was a 50:50 chance. :D

Wouldn't make much sense to introduce a new column just to write a value in it and never read it back out again and *then* forgetting to actually commit it, no? :grin:

**Comment by mutec** [comment]
One thing I learned the last years: I don't have to understand everything. :D

**Pull request closed without merging**
