### PR TITLE
Add Pages option type

### PR DESCRIPTION
**Pull request by ChristopherWalz**

### CODE REVIEW

**Comment by ChristopherWalz** [comment]
Any chance this is getting merged for before 3.1 release? I don't see any compatibility issues.

**Comment by dtdesign** [comment]
It would make much more sense to use a scrollable list with a search input, such as the page selection UI used when adding or editing boxes.

https://github.com/WoltLab/WCF/blob/c6af51a42d926e0c258fe82c5c0dd77138164863/wcfsetup/install/files/acp/templates/boxAdd.tpl#L431

**Comment by jens1o** [comment]
Any updates? I'd need this for a plugin :/

**Comment by ChristopherWalz** [comment]
I don't have time right now to implement it like alex wants to. So either way you update the pull request yourself or hope that woltlab implements in on their own.

**Pull request closed without merging**
