### PR TITLE
Update composer dependencies

### PR DESCRIPTION
**Pull request by TimWolla**
ad Purifier:

> The primary backwards-incompatible change is that HTML Purifier will now add rel="noreferrer" to all links with target attributes (you can disable this with %HTML.TargetNoReferrer.)

see also: https://github.com/WoltLab/WCF/pull/2119/files#diff-fbd783b9f31efdbd3ec5e07e7e23e98f

### CODE REVIEW

**Comment by TimWolla** [comment]
The emogrifier changes have been reviewed by me and are good to go.

**Comment by jens1o** [comment]
Is Parsedown obsolete, is not it?

**Comment by TimWolla** [comment]
> Is Parsedown obsolete, is not it?

It is not.

**Comment by jens1o** [comment]
Where is it used? Did I looked into the wrong "Core" files? Is it used by Forum?

**Comment by TimWolla** [comment]
> Where is it used? Did I looked into the wrong "Core" files? Is it used by Forum?

https://github.com/WoltLab/com.woltlab.wcf.exporter/blob/5107e490c2c58d9641357dd279e172ae7b4016cc/files/lib/system/exporter/NodeBB0xRedisExporter.class.php#L542

**Comment by jens1o** [comment]
Ah, there it is. Thanks!

**Pull request merged**
