### PR TITLE
Fix Youtube embed

### PR DESCRIPTION
**Pull request by SoftCreatR**
Videos are not playable erving them through youtube-nocookie.com, because the whole project seem to be abandoned (returns 404).

### CODE REVIEW

**Comment by SoftCreatR** [comment]
PUSH

Issue is severe now, because youtube-nocookie.com only returns 404.

**Comment by TimWolla** [comment]
> Issue is severe now, because youtube-nocookie.com only returns 404.

Cannot reproduce: https://www.youtube-nocookie.com/embed/JPAX32lgkrw?rel=0

**Comment by Stricted** [comment]
i can reproduce it on windows phone
http://puu.sh/gmPd1/33d9c45159.png

**Comment by joshuaruesweg** [comment]
Here is a thread about the problem. There are many customers which have the problem:  https://community.woltlab.com/thread/236497-youtube-videos-kann-man-nicht-mehr-anschauen/?postID=1423448#post1423448

**Pull request merged**
