### PR TITLE
Add contentItemMetaIcons template event

### PR DESCRIPTION
**Pull request by Krymonota**
n/t

### CODE REVIEW

**Comment by Krymonota** [comment]
Is there any chance that we'll ever see this template event in 5.2?

**Comment by Hanashi** [comment]
Why is this not merged, yet?

**Comment by dtdesign** [comment]
What is the purpose of this event, or to be more precise, what do you want to insert at this location? Events had been introduced sparsely with the redesigned layout in an effort to keep the design clean.

Although the framework offers a lot of flexibility, it is _heavily opinionated_. We see third party developers quite often adding things soley for the reason that they _can_ ,without reflecting if they _should_. Therefore, please briefly explain what you want to achieve by providing a meaningful reason.

**Comment by Krymonota** [comment]
The reason for this PR is my plugin [Reading Time Estimate for Articles](https://pluginstore.woltlab.com/file/3174-reading-time-estimate-for-articles/). Several users have requested to be able to see the reading time estimate in the article list. This would be the most appropriate place from my point of view and that of the users.

Personally, I don't think it's a good idea to limit flexibility in this way. After all, plugin developers simply offer additional functionality, and the user can decide whether to enable it or install the plugin at all.

**Comment by dtdesign** [comment]
Thank you for taking your time to explain it.

**Pull request merged**
