### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by jens1o**
I didn't found fileindex as a word through DuckDuckGo, everywhere it's referenced as file index.

### CODE REVIEW

**Comment by joshuaruesweg** [comment]
You should reduce this commit to one.

**Comment by jens1o** [comment]
Okey, I'll do so next time.

**Comment by joshuaruesweg** [comment]
Or you make a force push, to update this pull request and reduce the commit to one :P

**Comment by jens1o** [comment]
Okey, something went terrible wrong using force push...

**Comment by joshuaruesweg** [comment]
Yes, your branch is one commit behind WoltLab/WCF master. Have you reset the branch to WoltLab/WCF, then commited your changes again (because, obviously, your commit where removed with the reset) and pushed it?

**Comment by jens1o** [comment]
Ah... No. I thought it works in a different way. I'll do that again tomorrow, looking exactly who it works correctly. 😉 It was my first try. And failed.

**Pull request closed without merging**
