### PR TITLE
Fix noscript version of reCaptcha

### PR DESCRIPTION
**Pull request by SoftCreatR**
See https://community.woltlab.com/thread/247376-captcha-fallback-zu-klein

Current:

image

Fixed / Modified:

image

### CODE REVIEW

**Comment by TimWolla** [comment]
Where did you take the changes from? The HTML differs from the one at: https://developers.google.com/recaptcha/docs/faq#does-recaptcha-support-users-that-dont-have-javascript-enabled

**Comment by SoftCreatR** [comment]
I've made them by my own, a while ago, because you cannot adopt it 1:1 in WCF due to some CSS rule incompabilities.

**Comment by TimWolla** [comment]
Thanks.

**Comment by My1** [comment]
this change looks great. (b4 anyone asks: yes I'm the same My1 who posted the thread).

**Comment by My1** [comment]
by the way, will it kill the next update if I just patch this up myself (by using this new file directly)?

next patchday does take quite some time.

**Comment by TimWolla** [comment]
> by the way, will it kill the next update if I just patch this up myself (by using this new file directly)?

Unless you break the file system permissions you are able to replace the template without breaking the update.

**Comment by My1** [comment]
well it might have been like "oh this file is not what it was, let's not update to not break anything"

**Comment by SoftCreatR** [comment]
WCF is mercyless in this case.

**Comment by My1** [comment]
okay, well I know that upgrading phpbb can be a pain because of this (maybe not anymore, but at least it iirc was teh cae once) but well when plugins are made manually it's legit.

**Comment by TimWolla** [comment]
> well it might have been like "oh this file is not what it was, let's not update to not break anything"

You are not supposed to change anything in the file system at all, so there is no reason to keep track of checksums or anything.

**Pull request merged**
