### PR TITLE
Added missing comma in de.xml

### PR DESCRIPTION
**Pull request by Fighter456**
Behind the word `versucht` in the language variable `wcf.acp.option.exception_privacy.description` a comma was missing.

### CODE REVIEW

**Comment by ChristopherWalz** [comment]
Should there really be a comma? I don't think so?

**Comment by jens1o** [comment]
I think a comma is needed there.

**Comment by dtdesign** [comment]
There should be absolutely no comma.

**Comment by KittBlog** [comment]
There should be, of course. It’s an infinitive group without any helping verb and thus a comma must be added.

See also: https://www.studis-online.de/Studieren/Richtig_schreiben/komma_bei_infinitivgruppen.php

**Pull request closed without merging**
