### PR TITLE
Add Vimeo Embed Referrer Policy

### PR DESCRIPTION
**Pull request by SoftCreatR**
See https://www.woltlab.com/community/thread/295351-video-nicht-verf%C3%BCgbar-bei-sehr-vielen-youtube-videos/?postID=1891462#post1891462

### CODE REVIEW

**Comment by TimWolla** [comment]
It appears that I'm unable to reproduce this with the Vimeo videos I tested, but I was able to test this attribute with YouTube and I trust that this also solves the issue for Vimeo.

**Comment by SoftCreatR** [comment]
I had this problem with private Vimeo videos only.

I'll update the PR and add it to Youtube, too.

**Comment by TimWolla** [comment]
> I'll update the PR and add it to Youtube, too.

No need, I'll handle that (as I wanted to adjust the commit message anyway) :-)

**Comment by TimWolla** [comment]
Thanks. I've added you as a co-authored-by for YouTube, as I've missed the playlist provider myself.

**Pull request closed without merging**
