### PR TITLE
Update reactions & smilies (Twemoji)

### PR DESCRIPTION
**Pull request by SoftCreatR**
Replace EmojiOne assets with Twemoji (https://github.com/twitter/twemoji)

For compatibility reasons, paths and file names shouldn't change.

image

### CODE REVIEW

**Comment by cadeyrn** [comment]
Same question as in #4960: Why?

**Comment by SoftCreatR** [comment]
https://github.com/WoltLab/WCF/pull/4960#issuecomment-1214966885

The special feature of Twemoji is its widespread use (e.g. in discord and on Twitter itself).

**Comment by xopez** [comment]
+1 for this set.

**Comment by eveneme** [comment]
Or maybe twitter emojis?

**Comment by SoftCreatR** [comment]
> Or maybe twitter emojis?

These are the Twitter emoji?

**Comment by eveneme** [comment]
> > Or maybe twitter emojis?
> 
> These are the Twitter emoji?

https://twemoji.twitter.com

**Comment by SoftCreatR** [comment]
> > > Or maybe twitter emojis?
> > 
> > 
> > These are the Twitter emoji?
> > Yes sorry i bad read..
> > https://twemoji.twitter.com

I still don't get your point.

**Pull request closed without merging**
