### PR TITLE
Fix int length handling during DB updates for MySQL >= 8.0.19

### LINKED ISSUE #3160: MySQL 8.0.19: Incompatible changes to integer column definitions
> Display width specification for integer data types was deprecated in MySQL 8.0.17, and now statements that include data type definitions in their output no longer show the display width for integer types […]

See https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-19.html#mysqld-8-0-19-feature

This change causes `SHOW COLUMNS FROM …` to report columns `int`, `smallint` and `tinyint` (unless it is `tinyint(1)`) without any length whatsoever. In MySQL < 8.0.19 these columns would be reported as `int(10)`, `smallint(5)`, etc. The `DatabaseTableChangeProcessor` is unaware of this change, eventually causing an infinite loop during the upgrade 3.1 -> 5.2 when dealing with the `wcf1_media` table.

### PR DESCRIPTION
**Pull request by Gravatronics**
Close #3160

### CODE REVIEW

**Comment by dtdesign** [comment]
@TimWolla Technically, we can skip the version check and always ignore _differences_ in the length of integer values, right?

**Comment by TimWolla** [comment]
Yes, that's my understanding and that's what I wanted to suggest with my review. The “display length” of integer columns is only relevant when used in combination with the `ZEROFILL` option which is super obscure, non-standard and deprecated together with the display length in MySQL 8.0.17+.

**Comment by dtdesign** [comment]
@Gravatronics Please remove the version check and ignore the length unless it's `TINYINT(1)`.

**Comment by TimWolla** [comment]
And FWIW: Dumping a database with mysqldump on 8.0.19 will drop the integer widths as well. So anyone that ever was on a modern MySQL 8 will have “incorrect” values in there:

```
# mysqldump -p XXXX |grep AUTO_INCREMENT |head -n5
Enter password: 
  `blogID` int NOT NULL AUTO_INCREMENT,
  `coverPhotoID` int NOT NULL AUTO_INCREMENT,
  `entryID` int NOT NULL AUTO_INCREMENT,
  `coverPhotoID` int NOT NULL AUTO_INCREMENT,
  `eventID` int NOT NULL AUTO_INCREMENT,
```

**Pull request merged**
