### PR TITLE
Add ViewableUserOption#setOptionValue event

### PR DESCRIPTION
**Pull request by Sir-Will**
Add ViewableUserOption#setOptionValue event to allow option value manipulation.

While creating spam restrictions I was looking into restricting links in the profile of new users without preventing them from being able to create their profile with links. Unfortunately I couldn't find any way to accomplish that without additional events.

### CODE REVIEW

**Comment by TimWolla** [comment]
I believe @dtdesign's reply on the sibling issue also applies here: https://github.com/WoltLab/WCF/pull/4056#issuecomment-793092098

**Comment by dtdesign** [comment]
It is a bit odd to enforce the restrictions on runtime rather than preventing the values being set in the first place. This looks like you should reject the rogue data during validation when the user first enters them?

**Comment by Sir-Will** [comment]
The goal is to allow the users to fill out their profile without restrictions but protect other users from malicious links.
Depending on the activity of the user, the user will be promoted and the restrictions will be removed.

Rejecting any links while submitting would mean that the user would need to go back to the profile after the promotion, which creates a bad user experience.
The restrictions are also only visible to other users and not the user itself.

**Comment by dtdesign** [comment]
It is already possible to limit the editing capabilities to the user profile, opening up the customization options for some user groups only. From our experience this is an extremely powerful method to drive spammers away, but have little to no impact on actual users. It is also consistent by only allowing data to be entered if it is actually going to be displayed.

Your approach is quite awkward and contradicts the overall design principles of the UI/UX of the software. Please feel free to provide more arguments that strengthen your point.

**Comment by Sir-Will** [comment]
My approach:
1. User creates account
2. Fills out profile (profile shows link as plain text) 
3. Reads few threads and posts 
4. Gets promoted and the link is no longer being changed to plain text.

Not allowing to fill out the field approach:
1. User creates account
2. Fills out profile (except link related fields, users and staff get less information about the new user, meaning less info to determine if it's a spam user)
3. Reads few threads and posts
4. Gets promoted
5. Needs to be notified about new unlocked profile fields
6. Needs to go back to the profile to fill out the new profile fields

**Comment by Sir-Will** [comment]
I was able to achieve this now by using the OptionHandler#afterReadCache event and overwriting and extending the outputClass.

**Pull request closed without merging**
