### PR TITLE
Show DatePicker clear button on setDate

### PR DESCRIPTION
**Pull request by derpierre65**
after use e.g. $('#myDatePicker').datepicker('setDate', ...); the clear button doesnt appears, only on initialization

### CODE REVIEW

**Comment by TimWolla** [comment]
> $('#myDatePicker').datepicker('setDate', ...);

Using the DatePicker through jQuery is deprecated. This does not mean there isn't a bug here, though.

**Comment by derpierre65** [comment]
is that better now?

**Comment by TimWolla** [comment]
> is that better now?

This is better. Thank you.

I'm not merging this yet, because I want to make a real functional test in addition to just reading the code.

**Comment by joshuaruesweg** [comment]
Thanks!

**Pull request merged**
