### PR TITLE
pull gravatars via https

### PR DESCRIPTION
**Pull request by jens1o**
https://gravatar.com/avatar/8b464a8b587c833f435541619d605f40?s=200&r=g works quite fine, too.

### CODE REVIEW

**Comment by TimWolla** [comment]
Not every web hoster supports outgoing TLS connections.

**Comment by jens1o** [comment]
How are you going to do that with GitHub Auth Actions, Twitter, Google, and Facebook?

For example: https://github.com/WoltLab/WCF/blob/master/wcfsetup/install/files/lib/action/FacebookAuthAction.class.php#L48

**Comment by TimWolla** [comment]
> How are you going to do that with GitHub Auth Actions, Twitter, Google, and Facebook?

These require TLS from their side, this is documented as well and provides a real value add, because secrets are transmitted.

Gravatars OTOH transmit public information. While I agree that encrypting everything is a good thing in general in this case there are more downsides.

- Servers don't usually get MITMd anyway.
- The end user receives the Gravatar properly encrypted by WoltLab Suite.
- PHP may not support outgoing connections.
- It is not possible to re-use negotiated TLS sessions for multiple gravatar requests, because of PHP's shared nothing request model.

**Comment by jens1o** [comment]
Okay, I get your point.

**Pull request closed without merging**
