### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by jens1o**

### CODE REVIEW

**Comment by dtdesign** [comment]
Would you mind adjusting these occurrences too, so we have the entire fix in a single commit?

https://github.com/WoltLab/WCF/blob/c839bd496deec55ffc05dc9ad38165d84b6b8f41/wcfsetup/install/files/lib/core.functions.php#L190
https://github.com/WoltLab/WCF/blob/c839bd496deec55ffc05dc9ad38165d84b6b8f41/wcfsetup/install/lang/en.xml#L2884

**Comment by jens1o** [comment]
Yeah, absolutely.

**Comment by jens1o** [comment]
Shall I rebase or do you want to squash the commits?

**Comment by dtdesign** [comment]
I can do a squash + merge, but do whatever you feel comfortable with, I don't mind either.

**Comment by jens1o** [comment]
Okay then, I flipped a coin and it decided you may squash + merge then. 👅

**Comment by dtdesign** [comment]
Thanks.

**Pull request merged**
