### PR TITLE
Add sidebarRightBottom to the sidebar

### PR DESCRIPTION
**Pull request by Griborim**

### CODE REVIEW

**Comment by dtdesign** [comment]
There is already a suitable event in place, just a few lines down. What is the motivation behind this request?

**Comment by Griborim** [comment]
You can only Add Boxes on the Top from the sidebar with {capture assign='sidebarRight'}.

With {capture assign='sidebarRightBottom'} can you add Boxes after the loaded boxes.

**Comment by dtdesign** [comment]
The top placeholder is exclusively for static sidebar content, such as filter options on the thread list in the forums and similar. For all other purposes use a proper box that can then be freely arranged by the administrator.

**Comment by Griborim** [comment]
And what is with static Boxes after dynamic boxes?

**Comment by dtdesign** [comment]
Static boxes are those that can only be used on that specific page and they are designed to always appear at the top. I've already given you an example on what kind of boxes this covers, but everything beyond that should be a dynamic box.

**Pull request closed without merging**
