### PR TITLE
add "support-likes" attribute

### PR DESCRIPTION
**Pull request by joshuaruesweg**
atm it is not possible to have two commentLists on one page, without that both supports likes

### CODE REVIEW

**Comment by TimWolla** [comment]
Doing this vice versa would be better for backwards compatibility. We are in Beta already.

**Comment by joshuaruesweg** [comment]
And if this attribute isn't set, the default value is then ``0``?

**Comment by TimWolla** [comment]
> And if this attribute isn't set, the default value is then 0?

Yes. Otherwise every developer would have to add the attribute.

**Comment by joshuaruesweg** [comment]
I think every developer include the ``commentList.tpl``-Template. 

But I can rewrite this.

**Comment by TimWolla** [comment]
> I think every developer include the commentList.tpl-Template.

Looks like I missed that this was a general use template. I'll let @dtdesign decide.

**Comment by joshuaruesweg** [comment]
@TimWolla maybe this is a PR for `next` if @dtdesign won't decide ^^

**Pull request closed without merging**
